from __future__ import annotations

import logging
import threading
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from salamtak_core import (
    APP_NAME,
    APP_NAME_EN,
    GEMINI_MODEL,
    build_suggestions,
    clean_dataframe,
    get_chatbot_reply,
    load_medicines_data,
    normalize_text,
    standardize_doctors_schedule,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(APP_NAME_EN)

app = FastAPI(
    title=f"{APP_NAME_EN} Chatbot API",
    description="API-only chatbot service for Flutter/Web through a Node.js backend.",
    version="2.0.0",
)

# Adjust origins in production from Node.js / gateway settings.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

try:
    MEDICINES_DF, MEDICINES_SOURCE = load_medicines_data()
except Exception as exc:  # Fail fast because medicines must come from file only.
    logger.exception("Failed to load medicines data: %s", exc)
    MEDICINES_DF = clean_dataframe(__import__("pandas").DataFrame())
    MEDICINES_SOURCE = "not-loaded"
    STARTUP_ERROR = str(exc)
else:
    STARTUP_ERROR = ""


class ChatRequest(BaseModel):
    session_id: Optional[str] = Field(
        default=None,
        description="Stable client/session ID generated by Node.js or the app. If omitted, the API creates one.",
    )
    message: str = Field(..., min_length=1)
    language: Literal["ar", "en"] = Field(default="ar", description="User-selected UI language. Replies always follow this value.")
    doctors_schedule: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Doctor schedule rows coming from the Node.js backend/database. No internal doctor schedule is used.",
    )
    min_score: int = Field(default=55, ge=0, le=100)
    top_k: int = Field(default=3, ge=1, le=10)


class ChatResponse(BaseModel):
    session_id: str
    reply: str
    language: Literal["ar", "en"]
    intent: str
    matches_count: int
    model: str
    suggestions: List[str]
    state: Dict[str, Any]


class ClearSessionResponse(BaseModel):
    session_id: str
    cleared: bool


class SessionStateStore:
    """In-memory state per user session.

    The Node.js backend can also store this state externally by reusing the same
    session_id. This store only keeps lightweight conversation context needed for
    follow-up questions and symptom triage.
    """

    def __init__(self) -> None:
        self._lock = threading.RLock()
        self._sessions: Dict[str, Dict[str, Any]] = {}

    def get(self, session_id: str) -> Dict[str, Any]:
        with self._lock:
            if session_id not in self._sessions:
                self._sessions[session_id] = {
                    "messages": [],
                    "recent_questions": [],
                    "last_medicine": "",
                    "last_symptom": "",
                    "active_triage": None,
                    # Cached per-session doctor schedule. It is filled when the backend
                    # sends doctors_schedule for this session, reused on later messages,
                    # and deleted when the session is closed/cleared.
                    "doctors_schedule": [],
                    "doctors_schedule_updated_at": None,
                }
            return self._sessions[session_id]


    def update_doctors_schedule(self, session_id: str, doctors_schedule: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Cache the latest doctors schedule for this session only.

        The schedule is intentionally not persisted to a database. It lives only in
        memory and is removed with the rest of the session when /close or DELETE is
        called. If the backend sends an empty list, the previous cached schedule is
        kept so follow-up doctor questions can still work during the same session.
        """
        with self._lock:
            state = self.get(session_id)
            if doctors_schedule:
                state["doctors_schedule"] = doctors_schedule
                state["doctors_schedule_updated_at"] = datetime.now(timezone.utc).isoformat()
            return state

    def update_after_turn(self, session_id: str, question: str, reply: str, result: Dict[str, Any]) -> Dict[str, Any]:
        with self._lock:
            state = self.get(session_id)
            state["messages"].append({"role": "user", "content": question})
            state["messages"].append({"role": "assistant", "content": reply})
            normalized_question = normalize_text(question)
            recent = [item for item in state["recent_questions"] if normalize_text(item) != normalized_question]
            state["recent_questions"] = [question] + recent[:7]
            if result.get("primary_medicine"):
                state["last_medicine"] = str(result["primary_medicine"])
            if result.get("symptom_key"):
                state["last_symptom"] = str(result["symptom_key"])
            if "triage_state" in result:
                state["active_triage"] = result["triage_state"]
            elif state.get("active_triage") and result.get("intent") != "symptom_triage":
                state["active_triage"] = None
            return state

    def clear(self, session_id: str) -> bool:
        with self._lock:
            existed = session_id in self._sessions
            self._sessions.pop(session_id, None)
            return existed

    def count(self) -> int:
        with self._lock:
            return len(self._sessions)


SESSION_STORE = SessionStateStore()


@app.post("/chat", response_model=ChatResponse)
def chat(payload: ChatRequest) -> ChatResponse:
    if STARTUP_ERROR:
        raise HTTPException(status_code=500, detail=f"Medicines data failed to load: {STARTUP_ERROR}")

    session_id = payload.session_id or uuid.uuid4().hex
    state = SESSION_STORE.get(session_id)

    # If Node.js sends doctors_schedule in this request, cache it in the current
    # session. If it sends an empty list, reuse the latest cached schedule for
    # this same session. This allows the backend to send the schedule once when
    # the chat session starts, while keeping each user's schedule isolated.
    if payload.doctors_schedule:
        state = SESSION_STORE.update_doctors_schedule(session_id, payload.doctors_schedule)
    doctors_schedule_for_turn = state.get("doctors_schedule", [])
    doctors_df = standardize_doctors_schedule(doctors_schedule_for_turn)

    result = get_chatbot_reply(
        message=payload.message,
        medicines_df=MEDICINES_DF,
        doctors_df=doctors_df,
        top_k=payload.top_k,
        min_score=payload.min_score,
        recent_questions=state.get("recent_questions", []),
        last_medicine=state.get("last_medicine", ""),
        preferred_language=payload.language,
        active_triage=state.get("active_triage"),
    )

    reply = str(result.get("reply", ""))
    new_state = SESSION_STORE.update_after_turn(session_id, payload.message, reply, result)
    suggestions = build_suggestions(
        new_state.get("messages", []),
        new_state.get("recent_questions", []),
        payload.language,
        last_medicine=new_state.get("last_medicine", ""),
        active_triage=new_state.get("active_triage"),
    )

    return ChatResponse(
        session_id=session_id,
        reply=reply,
        language=payload.language,
        intent=str(result.get("intent", "unknown")),
        matches_count=int(result.get("matches_count", 0) or 0),
        model=str(result.get("model", GEMINI_MODEL)),
        suggestions=suggestions,
        state={
            "last_medicine": new_state.get("last_medicine", ""),
            "last_symptom": new_state.get("last_symptom", ""),
            "active_triage": new_state.get("active_triage"),
            "recent_questions": new_state.get("recent_questions", []),
            "doctors_schedule_cached_count": len(new_state.get("doctors_schedule", [])),
            "doctors_schedule_updated_at": new_state.get("doctors_schedule_updated_at"),
        },
    )


@app.post("/sessions/{session_id}/close", response_model=ClearSessionResponse)
def close_session(session_id: str) -> ClearSessionResponse:
    """Close a chat session and delete its temporary in-memory history and schedule."""
    return ClearSessionResponse(session_id=session_id, cleared=SESSION_STORE.clear(session_id))
